default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: newlywish_challenge_development

test:
  <<: *default
  database: newlywish_challenge_test

production:
  <<: *default
  database: newlywish_challenge_production
  username: newlywish_challenge
  password: <%= ENV['NEWLYWISH_CHALLENGE_DATABASE_PASSWORD'] %>
